v2.6.32.7-jf20 * Rebased on 2.6.32.7 * cb3: interrupt coalesing support reduces interrupt overhead in some   cases from 20,000 interrupts per second to 60, on the order of the   wakeup rate for the md resync thread. * ntb: rebased with latest ntb.  Contains updates for ntbeth for     fixing CB3 dma copies across ntb, support for multiple ntbeth     interfaces.
v2.6.32.1-jf19
* Rebased on 2.6.32.1
* [FIX] cb3: fix handling of p-disabled q-continuation operations in the
  (0 < source_count % 8 < 3) cases i.e. recovering/resyncing 11 and 12
  disk raid6 arrays.  Resolves invalid descriptor errors due to dmacount
  overrun.
* [FIX] cb3: remove cancel_work_sync() on error-polling-thread work
  entries, it is superseeded by destroy_workqueue(). Resolves kernel
  oops on driver shutdown.
* [FIX] cb3: reset channels at initialization time.  Resolves channel
  initialization failures after a dirty shutdown.
* [FIX] dmatest: set the minimum transfer length to the alignment size.
  Resolves zero-length request errors.
* [FIX] config: SMP on by default in jf_defconfig
* config: updated jfmin_defconfig
* async_tx: added explicit 11 and 12 disk cases to raid6test module

v2.6.32-rc8-jf18
* Rebased on 2.6.32-rc8
* B0 only release, all A0 workarounds removed
* cb3: error handling and support for pq-validate operations.  Since cb3
  does not support asynchronous error notifications a polling thread is
  added to monitor in flight pq-validate operations.  This thread sleeps
  for pq-validate events where the array is mostly clean i.e. integrity
  checks and resync after unclean shutdown.  It polls aggressively to
  handle channel halts when the array is mostly dirty i.e. initial sync
  and some rebuild scenarios.
* config: SMP on by default in jf_defconfig
* config: added jfmin_defconfig (reduced configuration) to tame build
  times (watch for missing drivers)
* [WORKAROUND] adr: move adr memory back to type-6 until the ACPI
  committee approved method is implemented in the BIOS (i.e. type-2,
  AddressRangeReserved, plus extended attributes).  The kernel will
  translate the extended attributes to type-6 to maintain backwards
  compatibility for now.

v2.6.32-rc5-jf17
* Rebased on 2.6.32-rc5 (cb3 driver merged upstream for 2.6.32)
* [FIX] cb3: Fix another corner case in the A0 fence emulation
* [FIX] cb3: jf_xfercap module parameter was not hooked up
* [FIX] md/raid6: handle holes in the paramater list to
  async_syndrome_val for the DDF raid6 layout
* [FIX] async_tx: handle the 6-disk and 7-disk recovery cases for the DDF
  raid6 layout (they mirror the 4 and 5-disk recovery case in the native
  layout)
* [FIX] async_tx: unmap dma mappings in the descriptor allocation failure path
  in async_mult() and async_sum_product()
* [FIX] async_tx: fix stack overflow in raid6test when 256 disks are
  specified.
* [FIX] cb3: support DCA (direct cache access) on JSP+TBG configurations
* [FIX] md/raid5,6: update mutlticore implementation to avoid a
  pathological stripe bouncing scenario.  Performance is now stable, but
  still less than the single threaded case.
* [FIX] md/raid5,6: close a potential live lock with disk failures in the
  external metadata case
* ntb: updated to the alpha2-rc1 relase of the ntb library
* ntbeth: interrupt coalescing
* cb3: cleanup false positive compilation warnings on older gcc releases (4.0.1)
* md/raid6, async_tx: cleanup: don't pass raid6_empty_page around, use NULL
  instead

v2.6.30.5-jf16.1
* cb3: Promoted the null-descriptor-appended-to-pq workaround from an A0
  workaround to the production code for B0.  Originally it was there to
  cover for broken pq interrupts on A0.  However, on B0 the ordering of
  completion writes between legacy (memcpy) operations and raid operations
  is not guaranteed, so the workaround is needed to force all completion
  writes to originate from the legacy logic to ensure ordering.
* cb3: Added support for autoloading the driver module via udev

v2.6.30.5-jf16
* Rebased on 2.6.30.5
* [FIX] cb3: Corrected cases where the driver performed descriptor ring
  pointer arithmetic without masking the result against the ring size.  This lead
  to invalid updates of the DMACOUNT register.  The fence emulation workaround
  mostly covered this bug on Jasper Forest, stress testing on Tylersburg
  uncovered the issue.
* [FIX] cb1: Fixed a regression introduced by the change to move all
  descriptor allocation to the ->prep routine instead of ->submit.  The driver
  was not clearing the ->next field in the hardware descriptor to mark the end
  of the chain.
* cb3: Changed fence handling to be an explicit flag passed by users of the
  async_tx api rather than implicitly determined from the presence of a
  dependency chain.  This allows dependency chains that are strictly for
  completion ordering (no data dependency) to run unfenced.
* cb3: Added a sysfs interface to monitor descriptor ring statistics.  See the
  'quickdata' directory for each channel under /sys/class/dma
* cb3: New dynamic descriptor ring resize support now does not require channel
  'suspend' operations.   Previously this functionality was turned off on A0
  due its suspend related errata.
* [FIX] ntb: Fix for cq operation in the cq wraps that might cause some race
  conditions
* [FIX] ntb: Loading of ntbeth when no NTB device present in the system.
* ntb: Updated license headers to indicate Dual BSD/GPL
* ntb: Add support for using CB3 DMA for packet copying
* ntb: Add support for packet stats on ntb interface

v2.6.30.4-jf15.1
* [FIX] cb3: The zero-buffer, used to workaround the A0 restriction that all
  operations must operate on 8 source addresses, is statically allocated in the
  driver.  This is fine when the driver is compiled-in to the kernel, but when
  it is a module this static allocation comes from vmalloc'd memory.  The DMA
  mapping API does not return a valid DMA address translation for this
  memory, leading to data potential corruption when non-zero data is written
  to this incorrect physical address.
* [FIX] cb3: The driver was not correctly unmapping DMA addresses for P+Q
  operations.  This only impacts the VT-d case, or systems with >3GB of
  memory.  Otherwise DMA unmapping is a no-op.
* [FIX] raid6: Closed a potential assertion in the parity checking code
* Other minor coding-style cleanups and compilation warning fix for the bbu
  driver.

v2.6.30.4-jf15
* Rebased on 2.6.30.4
* Optimized the cb3 software ring entry to only consume 1-cacheline
* [FIX] cb3: For B0, fence operations need their own descriptor as they block
  future descriptors from executing until the previous descriptor has
  completed.
* cb3: Converted channel watchdog and reset handler from a workqueue to a
* timer.
* cb3: Modified the descriptor clean up path to hold off while the descriptor
  lock is contended (cpu utilization optimization).
* cb3: For B0, added dynamic ring resizing (shrink and expand).  Note
  this is disabled on A0 due to broken suspend support
* cb3: relicensed the raid portion of the driver under a dual BSD/GPLv2
  license
* [FIX] cb3: Fixed running pq transactions that are larger than the hardware
  maximum (xfercap).
* [FIX] pageattr: Root caused an ADR driver initialization failure to a
  regression introduced in the 2.6.30.  Backported the current fix from
  the 2.6.31-rc5 kernel
* [FIX] bbu: fixed "kernel BUG at fs/inode.c:1264!" due to calling
  bdput() on a block device that has already been handled by
  blkdev_put()
* [FIX] bbu: fixed io hang due to circular dependency on taking the
  backing-block-device reference.  The bbu driver must now be
  unregistered via userspace writing '0' to /sys/block/mdX/md/bbu, i.e. it
  is no longer automatic.
* [FIX] bbu: fixed writeback hang due to inverted logic test when
  determining whether the number of active-dirty cache entries
  has fallen below the writeback watermark.
* bbu: updated Documentation/blockdev/bbu.txt with details of all the
  sysfs knobs for bbu caches.
* ntb: updated to latest snapshot, details in latest ntb driver release notes

v2.6.29.6-jf14.1
* [FIX] cb3: initialize the flags for the A0 workaround pq completion
  descriptors to prevent a fence request from leaking in and causing a
  deadlock.

v2.6.29.6-jf14
* raid456: moved raid buffer addresses and spare page to a percpu allocation
* raid456: Enabled multicore processing
* [FIX] cb3: Added write barrier before notifying the cb3 engine of updated
  descriptors
* async_pq: added spare page parameter to async_syndrome_val to allow reuse of
  the percpu allocated spare page from the raid stack
* [FIX] dmaengine: the implementation for handling pq continuations was
  missing consideration for the P-disabled case
* [FIX] iop-adma: handle P-disabled PQ continuations
* [FIX] cb3: handle P-disabled PQ continuations
* [FIX] cb2: fix reset handler for the engine hang case (net_dma regression)
* [FIX] async_raid6_recov: implement special case handlers for the 4-disk and
  5-disk raid6 recovery case as these generate operations with a source count
  less than 2 (i.e. cb3 invalid) with the standard N-disk algorithm.
* raid6test: added test cases for 4-disk, 5-disk, and D+Q recovery
* [FIX] async_tx: removed the need to walk the parent chain when synchronously
  waiting for a transaction to complete (allows for a lighter weight 'issue
  pending' implementation for dependency chains).
* [FIX] iop-adma: teach lockdep about the locking hierarchy of inter-channel
  dependency handling
* [FIX] cb3: emulated fencing (Jasper Forest A0 workaround) was broken in a
  few ways:
  1/ pq operations were unconditionally clearing the emulated fence bit on the
     last descriptor in the chain, disregarding the case where the first and last
     descriptor are the same
  2/ interrupt operations were not hiding the hardware fence bit from the
     hardware
  3/ The emulated fence handler was not handling ring buffer index rollover
     correctly
* [FIX] cb3: disabled error completions and error interrupts for A0 Jasper
  Forest builds
* [FIX] raid456: closed small memory leak of the raid6 spare page
* ntb: Included a snapshot of the ntbeth driver

v2.6.29.5-jf13.1
* Fixed a gcc-4.3 compilation warning in the e820 code
* Fixed kernel oops when loading the ioatdma driver on an ioat1 platform
* Fixed MD compilation error when the bbu driver is disabled

v2.6.29.5-jf13
* Implemented the io path for the bbu driver with the following operations
  verified: read-miss, read-hit-dirty, read-hit-clean, write, and flush.
  Remaining item to test is lru eviction of dirty cache entries.  Also, two
  items remain to be implemented: 1/ modify mdadm to automate initial
  associations at first array startup and flush dirty entries at shutdown 2/
  Toggle arming of the ADR trigger to skip ADR entry on a graceful shutdown.
* See Documentation/blockdev/bbu.txt for usage instructions.
* Added a module parameter to enable testing of smaller transfer sizes
  with the ioatdma driver.  At load time specify 'jf_xfercap' to
  override the hardware XFERCAP register value.  The value in this
  register is the log base 2 value of the transfer size.  For example to
  limit operations to 512 bytes:

	modprobe ioatdma jf_xfercap=9

v2.6.29.4-jf12.1
* Readded the pci-mmconfig workaround as the bios with the microcode update is
  not widely available

v2.6.29.4-jf12
* Added ADR region detection.  For testing purposes, until the BIOS is ready,
  the ADR region will need to be specified manually with a kernel command line
  option with the format:

	memmap=<size>!<address>

  Where <address> is replaced with a free memory region that is ADR protected.
  A good starting point is an address above 64MB that shows up as "System RAM"
  in the output of:

	cat /proc/iomem

  Example: memmap=64M!0x78000000

  Note: Checkout of this functionality was performed with a
  virtualized (KVM) environment.

* Added a preview release of the 'bbu' driver.  bbu is responsible for
  partitioning ADR memory into separate caches and enabling those
  regions to be used as write-caches for md-raid devices (currently only
  raid5).  The management path is working in this code, put the i/o path
  is not included.  All accesses to a properly registered bbu cache will
  return an i/o error in this release.  See Documentation/blockdev/bbu.txt
  for usage information.


v2.6.29.3-jf11.1
* bug fix for the 4 disk raid6 case (incorrect count specified to
  async_syndrome_val())
* iop-adma driver fixes for pq operation
* various cleanups as a result of community feedback

v2.6.29.3-jf11
* Rebased on latest stable kernel 2.6.29.3
* Added 'raid6test' to exercise asynchronous raid6 recovery routines in
  a standalone module.  It simulates all the possible 2-disk failure
  combinations of a 16-disk array.
* Changed the 'src_cnt' parameter to 'disks' the difference being that
  callers now identify the full size of the 'blocks' array rather than
  having P and Q at implied locations.
* Fixed do_sync_gen_syndrome()'s handling of 'raid6 zero blocks'
* Fixed async_syndrome_val() to restore the 'blocks' array so that
  callers that go through the trouble of specifying a scribble region
  can rely on 'blocks' having the same contents upon return.
* async_raid6_2data_recov() and async_raid6_datap_recov() were missing
  calls to async_tx_sync_epilog() for the submit->scribble == NULL case.
* Fixed async_find_channel() with an A0 Jasper workaround to *not* find
  a channel for validate operations.
* Fixed a subtle bug in do_async_gen_syndrome() that would cause incorrect
  results when specifying 'raid6 zero blocks' in a transaction.

v2.6.29.2-jf10
* Fixed 'issued' descriptor tracking for A0 fence emulation
* Fixed fence tracking to use a software flag.  Using the hardware flag
  causes engine hangs for PQ operations.
* Fixed callbacks from 'interrupt' operations (async_trigger_callback)
  which resolves md-raid5 resync and write traffic hangs
* Quieted out-of-descriptor messages which occur regularly.  The
  capacity of the descriptor ring has been increased to 512 from 256.
  The optimal size depends on the raid array's stripe_cache_size.  This
  optimization work will be delayed until B0 silicon arrives.

v2.6.29.2-jf9
* Fixed zeroing of the source padding regions
* jf_defconfig now configures the kernel to enable an NFS root filesystem
* Worked around descriptor allocation failures due to fence and
  xor-completion-interrupt emulation

v2.6.29.2-jf8
* Fixed cases where the 'scribble' regions provided for the A0
  workaround case were not properly dword aligned.
* Fixed allocation of the A0 scribble regions to be page aligned and
  refcounted
* Fixed dmatest to only attempt 256-byte or 4K-byte xor/pq transactions

v2.6.29.1-jf7
* Rewrote the ioat2 and ioat3 implementations to use a native ring
  buffer.  This reduces the overhead of managing descriptors, and makes
  it possible to implement software simulated fence support.  It also
  allows pure NET_DMA channels to avoid any raid overhead by allowing an
  ioat3 channel to be in full raid mode or ioat2 memcpy only mode.
* With the removal of chain mode the async_tx channel allocator is
  updated to preclude the need to manage channel switching.  Now all
  requests from the raid code receive a 'full raid' channel.  This is
  based on a configuration option selected by the driver
  (ARCH_REQUIRES_NO_CHANNEL_SWITCH).
* All configuration cycles to the other Tylersburg (bus 0x80 - 0xfe) are
  performed via the mmconfig region regardless of the 'forcemm'
  parameter.  This patch may be removed in a future release once the
  microcode has been updated to allow io-port access to bus 0x80.
* Contrary to the statement in the v2.6.29.1-jf6 release the ioat driver
  has been updated with workarounds for A0 issues.  Running "make
  jf_defconfig" will automatically set CONFIG_JASPER_FOREST_A0=y.  The
  unit test results as of this release are:
  PLATFORM	MODE	TEST		RESULT
  Greencity	ioat2	copy-self-test	PASS
  Greencity	jf-a0	copy-self-test	PASS
  Greencity	ioat2	dmatest-copy	PASS
  Greencity	jf-a0	dmatest-copy	PASS
  Wahweap	jf-a0	copy-self-test	PASS
  Wahweap	jf-a0	xor-self-test	PASS
  Wahweap	jf-a0	dmatest-all	FAIL
* Added COPYING-NOTICE to the top-level directory for compliance with
  the BKM for Pre-Release Embargo of Open Source Software

v2.6.29.1-jf6
This release brings a few api changes as a result of community review of
the raid6 acceleration pieces.
* rebased on 2.6.29.1
* [api change]: All async_tx routines now take an async_submit_ctl
  pointer parameter.  This cleans up the prototypes and allows callers to pass
  in memory to be utilized for dma and page address converions
* [api change]: 'zero sum' operations and capabilities have been renamed
  to 'val' (for validate).  This reflects that in the pq case the
  compare targets need to be explicitly called out.
* [api change]: The 'scf' parameter to pq routines is now const to
  prevent manipulation of the system coeffecient tables.
* [api change]: The ASYNC_TX_DEP_ACK flag is removed.  Dependecy descriptors
  are now always acked at submission time.
* The ioat3 driver will fallback to using q-disabled-pq if the channel does not
  advertise xor.
* The async_tx api will now pass a DMA_PREP_FENCE flag to the driver
  when the descriptor-fence-bit needs to be set.
* There is no support, and no plans for support, of A0-silicon PQ-operation
  errata.  Interrupts, completion writebacks, and descriptor error handling are
  fundamental mechanisms of the driver.

v2.6.29-jf5
* rebased on v2.6.29-final
* ioat3.2 rewrite to fix descriptor chaining and simplify the implementation
* additional raid updates that went upstream during the 2.6.30 window

v2.6.29-rc8-jf4
* fixed up and hooked up xor/pq 'prep' methods
* fixed the self test to use a 'completion' like the memcpy case

v2.6.29-rc8-jf3
* rebased on 2.6.29-rc8
* reverted "ioat 2 prep calls reserve all descriptors" as it caused the
  self-test to fail, and was broken in other ways.

v2.6.29-rc7-jf2
* rebased on 2.6.29-rc7
* rebased on latest raid6 updates
* includes new interrupt, xor, a p+q tests in dmatest
* includes raid enabled cb3 driver via raidlib

v2.6.29-rc1-jf1 - Initial Jasper Forest Kernel
* async_tx and md raid updates for raid6
* pared down kernel config (jf_defconfig)
* based on 2.6.29-rc1

Signed-off-by: Dan Williams <dan.j.williams@intel.com>